<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubcategoriaXMarcas extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('subcategories_x_marcas')->insert([
           [ 'subcat_id' => 1, 'marca_id' =>1],
           [ 'subcat_id' => 1, 'marca_id' =>4],
           [ 'subcat_id' => 1, 'marca_id' =>3],
           [ 'subcat_id' => 1, 'marca_id' =>5],
           [ 'subcat_id' => 2, 'marca_id' =>1],
           [ 'subcat_id' => 2, 'marca_id' =>3],
           [ 'subcat_id' => 2, 'marca_id' =>14],
           [ 'subcat_id' => 2, 'marca_id' =>5],
           [ 'subcat_id' => 2, 'marca_id' =>30],
           [ 'subcat_id' => 2, 'marca_id' =>34],
           [ 'subcat_id' => 2, 'marca_id' =>31],
           [ 'subcat_id' => 2, 'marca_id' =>29],
           [ 'subcat_id' => 2, 'marca_id' =>23],
           [ 'subcat_id' => 3, 'marca_id' =>1],
           [ 'subcat_id' => 3, 'marca_id' =>3],
           [ 'subcat_id' => 3, 'marca_id' =>4],
           [ 'subcat_id' => 4, 'marca_id' =>1],
           [ 'subcat_id' => 4, 'marca_id' =>3],
           [ 'subcat_id' => 4, 'marca_id' =>14],
           [ 'subcat_id' => 4, 'marca_id' =>5],
           [ 'subcat_id' => 4, 'marca_id' =>30],
           [ 'subcat_id' => 4, 'marca_id' =>29],
           [ 'subcat_id' => 4, 'marca_id' =>31],
           [ 'subcat_id' => 5, 'marca_id' =>1],
           [ 'subcat_id' => 5, 'marca_id' =>3],
           [ 'subcat_id' => 5, 'marca_id' =>14],
           [ 'subcat_id' => 5, 'marca_id' =>29],
           [ 'subcat_id' => 5, 'marca_id' =>30],
           [ 'subcat_id' => 5, 'marca_id' =>23],
           [ 'subcat_id' => 6, 'marca_id' =>2],
           [ 'subcat_id' => 6, 'marca_id' =>4],
           [ 'subcat_id' => 6, 'marca_id' =>5],
           [ 'subcat_id' => 6, 'marca_id' =>30],
           [ 'subcat_id' => 7, 'marca_id' =>1	],
           [ 'subcat_id' => 7, 'marca_id' =>14	],
           [ 'subcat_id' => 7, 'marca_id' =>5	],
           [ 'subcat_id' => 7, 'marca_id' =>30	],
           [ 'subcat_id' => 7, 'marca_id' =>31	],
           [ 'subcat_id' => 7, 'marca_id' =>34],
           [ 'subcat_id' => 8, 'marca_id' =>1],
           [ 'subcat_id' => 8, 'marca_id' =>14],
           [ 'subcat_id' => 8, 'marca_id' =>23],
           [ 'subcat_id' => 8, 'marca_id' =>30],
           [ 'subcat_id' => 8, 'marca_id' =>31],
           [ 'subcat_id' => 8, 'marca_id' =>29],
           [ 'subcat_id' => 9, 'marca_id' =>1],
           [ 'subcat_id' => 9, 'marca_id' =>4],
           [ 'subcat_id' => 9, 'marca_id' =>3],
           [ 'subcat_id' => 9, 'marca_id' =>5],			
           [ 'subcat_id' => 10, 'marca_id' =>1],			
           [ 'subcat_id' => 10, 'marca_id' =>4],			
           [ 'subcat_id' => 10, 'marca_id' =>5],			
           [ 'subcat_id' => 11, 'marca_id' =>3],			
           [ 'subcat_id' => 11, 'marca_id' =>4],			
           [ 'subcat_id' => 12, 'marca_id' =>4],			
           [ 'subcat_id' => 13, 'marca_id' =>4],			
           [ 'subcat_id' => 14, 'marca_id' =>1],			
           [ 'subcat_id' => 14, 'marca_id' =>4],			
           [ 'subcat_id' => 14, 'marca_id' =>24],			
           [ 'subcat_id' => 15, 'marca_id' =>5],			
           [ 'subcat_id' => 16, 'marca_id' =>1],			
           [ 'subcat_id' => 16, 'marca_id' =>16],			
           [ 'subcat_id' => 17, 'marca_id' =>1],			
           [ 'subcat_id' => 17, 'marca_id' =>16],			
           [ 'subcat_id' => 17, 'marca_id' =>13],			
           [ 'subcat_id' => 17, 'marca_id' =>31],			
           [ 'subcat_id' => 18, 'marca_id' =>1],			
           [ 'subcat_id' => 18, 'marca_id' =>16],			
           [ 'subcat_id' => 18, 'marca_id' =>13],			
           [ 'subcat_id' => 18, 'marca_id' =>31],			
           [ 'subcat_id' => 18, 'marca_id' =>6],			
           [ 'subcat_id' => 18, 'marca_id' =>18],			
           [ 'subcat_id' => 18, 'marca_id' =>22],									
           [ 'subcat_id' => 19, 'marca_id' =>6],													
           [ 'subcat_id' => 19, 'marca_id' =>16],									
           [ 'subcat_id' => 19, 'marca_id' =>13],									
           [ 'subcat_id' => 19, 'marca_id' =>31],									
           [ 'subcat_id' => 19, 'marca_id' =>22],									
           [ 'subcat_id' => 20, 'marca_id' =>1],									
           [ 'subcat_id' => 20, 'marca_id' =>13],									
           [ 'subcat_id' => 20, 'marca_id' =>25],									
           [ 'subcat_id' => 21, 'marca_id' =>13],												
           [ 'subcat_id' => 21, 'marca_id' =>18],									
           [ 'subcat_id' => 21, 'marca_id' =>26],									
           [ 'subcat_id' => 21, 'marca_id' =>6],									
           [ 'subcat_id' => 22, 'marca_id' =>7],									
           [ 'subcat_id' => 22, 'marca_id' =>19],									
           [ 'subcat_id' => 22, 'marca_id' =>27],									
           [ 'subcat_id' => 23, 'marca_id' =>8],									
           [ 'subcat_id' => 23, 'marca_id' =>20],									
           [ 'subcat_id' => 23, 'marca_id' =>7],									
           [ 'subcat_id' => 23, 'marca_id' =>32],									
           [ 'subcat_id' => 23, 'marca_id' =>19],									
           [ 'subcat_id' => 23, 'marca_id' =>17],									
           [ 'subcat_id' => 23, 'marca_id' =>1],									
           [ 'subcat_id' => 23, 'marca_id' =>35],									
           [ 'subcat_id' => 23, 'marca_id' =>6],
           [ 'subcat_id' => 24, 'marca_id' =>8],									
           [ 'subcat_id' => 24, 'marca_id' =>20],									
           [ 'subcat_id' => 24, 'marca_id' =>7],									
           [ 'subcat_id' => 24, 'marca_id' =>32],									
           [ 'subcat_id' => 24, 'marca_id' =>19],									
           [ 'subcat_id' => 24, 'marca_id' =>17],									
           [ 'subcat_id' => 24, 'marca_id' =>1],									
           [ 'subcat_id' => 24, 'marca_id' =>35],									
           [ 'subcat_id' => 24, 'marca_id' =>6],	
           [ 'subcat_id' => 25, 'marca_id' =>8],	
           [ 'subcat_id' => 25, 'marca_id' =>20],	
           [ 'subcat_id' => 25, 'marca_id' =>7],	
           [ 'subcat_id' => 25, 'marca_id' =>32],	
           [ 'subcat_id' => 25, 'marca_id' =>19],	
           [ 'subcat_id' => 25, 'marca_id' =>17],	
           [ 'subcat_id' => 25, 'marca_id' =>6],	
           [ 'subcat_id' => 25, 'marca_id' =>35],	
           [ 'subcat_id' => 26, 'marca_id' =>8],									
           [ 'subcat_id' => 26, 'marca_id' =>20],									
           [ 'subcat_id' => 26, 'marca_id' =>7],									
           [ 'subcat_id' => 26, 'marca_id' =>32],									
           [ 'subcat_id' => 26, 'marca_id' =>19],									
           [ 'subcat_id' => 26, 'marca_id' =>17],									
           [ 'subcat_id' => 26, 'marca_id' =>15],									
           [ 'subcat_id' => 26, 'marca_id' =>35],									
           [ 'subcat_id' => 26, 'marca_id' =>6],
           [ 'subcat_id' => 27, 'marca_id' =>9],
           [ 'subcat_id' => 27, 'marca_id' =>21],
           [ 'subcat_id' => 27, 'marca_id' =>7],
           [ 'subcat_id' => 27, 'marca_id' =>32],
           [ 'subcat_id' => 27, 'marca_id' =>19],
           [ 'subcat_id' => 27, 'marca_id' =>17],
           [ 'subcat_id' => 28, 'marca_id' =>10],
           [ 'subcat_id' => 28, 'marca_id' =>22],
           [ 'subcat_id' => 28, 'marca_id' =>28],
           [ 'subcat_id' => 29, 'marca_id' =>11],
           [ 'subcat_id' => 29, 'marca_id' =>6],
           [ 'subcat_id' => 29, 'marca_id' =>7],
           [ 'subcat_id' => 29, 'marca_id' =>8],
           [ 'subcat_id' => 29, 'marca_id' =>33],
           [ 'subcat_id' => 30, 'marca_id' =>12],
           				
        ]);
    }
}
